### ISSUE TITLE
The StringIndexerModelConverter stores labels instead of indices in .pmml file, right?

### ISSUE THREAD

**Issue by hibayesian** [jpmml/jpmml-sparkml#10]
Sorry to bother you again.

The schema of training data is as follows:
column: a1; data type: double; role: feature
column: a2; data type: double; role: feature
column: a3; data type: double; role: label

And there are only two values(-1.0, 1.0) in the label column(a3).

In order to train a pipeline, I put StringIndexer, VectorIndexer and Decision Tree Classifier together.
` new Pipeline()
        .setStages(Array(labelIndexer, vectorIndexer, classifier))`

After fitted the pipeline, the model is tranformed to pmml.
`ConverterUtil.toPMML(schema, model.model.asInstanceOf[PipelineModel])` 

What confuesed me is that StringIndexerModelConverter stores the labels("-1.0" and "1.0") in the pmml file instead of indices of labels("0" and "1"). Is it right? Then how jpmml-sparkml transforms the labels to indices? I just cannot find the related code. Sad...

```
<PMML xmlns="http://www.dmg.org/PMML-4_2" version="4.2">
    <Header>
        <Application/>
        <Timestamp>2017-02-20T03:17:32Z</Timestamp>
    </Header>
    <DataDictionary>
        <DataField name="a3" optype="categorical" dataType="double">
            <Value value="-1.0"/>
            <Value value="1.0"/>
        </DataField>
        <DataField name="a1" optype="continuous" dataType="double"/>
        <DataField name="a2" optype="continuous" dataType="double"/>
        <DataField name="prediction" optype="categorical" dataType="double"/>
    </DataDictionary>
    <TreeModel functionName="classification" splitCharacteristic="binarySplit">
        <MiningSchema>
            <MiningField name="a3" usageType="target"/>
        </MiningSchema>
        <Output>
            <OutputField name="probability_-1.0" feature="probability" value="-1.0"/>
            <OutputField name="probability_1.0" feature="probability" value="1.0"/>
        </Output>
        <Node score="-1.0" recordCount="5300.0">
            <True/>
            <ScoreDistribution value="-1.0" recordCount="2924.0"/>
            <ScoreDistribution value="1.0" recordCount="2376.0"/>
        </Node>
    </TreeModel>
</PMML>
```

Another question is that does jpmml-spark supports loading a pipleline model(including transformers and a classifier or a regressor) from pmml file? I use jpmml-spark to load the above pipeline model from the pmml file, but it seems the StringIndexerModel doesn't work correctly.

Looking forward to your reply. Thanks a lot!

**Comment by vruusmann** [comment]
> What confuesed me is that StringIndexerModelConverter stores the labels("-1.0" and "1.0") in the pmml file instead of indices of labels("0" and "1"). Is it right?

Apache Spark doesn't support string columns. It uses a workaround, where 1) the string column is converted to a temporary Vector column using `StringIndexer`, 2) the model is trained using this Vector column as label/feature and 3) the index of some "interesting" vector element is converted back to string column using `IndexToString`.

PMML supports string values directly. It doesn't need any of those string-vector-string helper transformations.

> Then how jpmml-sparkml transforms the labels to indices? I just cannot find the related code.

See `StringIndexerModelConverter` and `IndexToStringConverter`.

Why do you need to investigate the "internals" of the JPMML-SparkML library? As an end user, you're only supposed to interact with the `ConverterUtil#toPMML(StructType, PipelineModel)` utility method. The returned `org.dmg.pmml.PMML` class model object is a complete description of your `PipelineModel` object in PMML language. There is no need to proof-read or manually edit it afterwards.

> Another question is that does jpmml-spark supports loading a pipleline model(including transformers and a classifier or a regressor) from pmml file?

You cannot "parse" PMML documents into Apache Spark `PipelineModel` objects. Today, PMML is simply so much more flexible and feature-rich that Apache Spark (eg. Apache Spark cannot represent/handle such triviality as a decision tree, where the decisioning path is determined by performing multi-way splits on string features).

You can execute PMML documents "natively" using the [JPMML-Spark](https://github.com/jpmml/jpmml-spark) library.
