### ISSUE TITLE
LightGBM integration

### ISSUE THREAD

**Issue by Archmagegck** [jpmml/jpmml-sparkml#107]
My dataset contains some string features, and I used StringIndexers to encode them. When I put the StringIndexers, VectorAssembler, and LightGBM in a pipeline, and fit the pipeline, everything is ok. 
![image](https://user-images.githubusercontent.com/8872911/108465440-fc76e300-72bc-11eb-9e60-1b639d6ac93d.png)

But, when I want to saved the pipeline into PMML, an error occurred. The error log is: Py4JJavaError: An error occurred while calling o16875.buildFile. : java.lang.IllegalArgumentException: Field devinfov3_general_data_locale_iso_3_country has data type string
![image](https://user-images.githubusercontent.com/8872911/108465450-026cc400-72bd-11eb-95cd-16239f2dd943.png)

devinfov3_general_data_locale_iso_3_country is one of the string features.

**Comment by vruusmann** [comment]
You can probably work around this specific error message by "downgrading" categorical features from to the one-hot-encoded representation (`StringIndexer + OneHotEncoder`).

In the long term, the JPMML-SparkML library should include a specialized LightGBM integration (that knows about LightGBM's ability to accept categorical features as-is).

**Comment by Archmagegck** [comment]
I'm sorry for I open the issue in a wrong place. Actually, this is an issue for jpmml-lightgbm. I have tried StringIndexer + OneHotEncoder to encode the string features, but the problem persists. I opened a new issue at jpmml-lightgbm(https://github.com/jpmml/jpmml-lightgbm/issues/47).

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-sparkml/commit/7635defa820eb4a7484adcf200d9ba2c41f57ff5
