### ISSUE TITLE
StringIndexerModelConverter gives java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by liumy601** [jpmml/jpmml-sparkml#119]
Hi,

I got a weird problem when i transform a string type feature, the stack trace is below:
```
java.lang.IllegalArgumentException
	at org.jpmml.converter.InvalidValueDecorator.<init>(InvalidValueDecorator.java:36)
	at org.jpmml.sparkml.feature.StringIndexerModelConverter.encodeFeatures(StringIndexerModelConverter.java:94)
	at org.jpmml.sparkml.FeatureConverter.registerFeatures(FeatureConverter.java:54)
	at org.jpmml.sparkml.PMMLBuilder.build(PMMLBuilder.java:118)
	at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:283)
	at org.jpmml.sparkml.PMMLBuilder.buildByteArray(PMMLBuilder.java:279)
	at com.vip.imp.algs.XgbRank.<init>(XgbRank.java:309)
```

i used jpmml-sparkml 1.6.6, spark 3.0.1, but the same code works on jpmml-sparkml 1.4.17 and spark 2.3, and the code is like this:
```java
List<String> indexCols = new ArrayList<>();
for (String col: toIndexAliasCols) {
	StringIndexer indexer = new StringIndexer().setInputCol(col).setOutputCol(col+"_index").setHandleInvalid("keep");
	indexCols.add(col+"_index");
	stages.add(indexer);
}

String[] ohInputCols = new String[indexCols.size()];
indexCols.toArray(ohInputCols);
String[] ohOutputCols = new String[ohInputCols.length];
for (int i=0; i<ohInputCols.length; i++) {
	ohOutputCols[i] = ohInputCols[i]+"_vec";
}
```

please help, i'm axious.

**Comment by vruusmann** [comment]
This is issue is related to https://github.com/jpmml/sklearn2pmml/issues/298

In brief, older JPMML-Converter library versions permitted the use of `InvalidValueTreatment.AS_IS` with invalid value replacement. However, only `InvalidValueTreatment.AS_VALUE` should be permitted.

Anyway, your stack trace doesn't make sense. There is no way how in JPMML-SparkML version 1.6.6 the `invalidCategory` local variable could have a `null` value there:
https://github.com/jpmml/jpmml-sparkml/blob/1.6.6/src/main/java/org/jpmml/sparkml/feature/StringIndexerModelConverter.java#L94

**Comment by vruusmann** [comment]
The conflict happens because of `StringIndexer#setHandleInvalid("keep")`. If your pipeline allows you to do so, consider switching to `StringIndexer#setHandleInvalid("error")`.

However, it still looks like a JPMML-SparkML vs. JPMML-Converter library mismatch on your side. The `HEAD` version of the JPMML-SparkML 1.6.X development branch looks correct to me.

**Comment by liumy601** [comment]
Thanks for your quick reply.

I also doubt the mismatch of jpmml version, i used spark 3.0.1 and these jpmml poms:
        jpmml-sparkml 1.6.6
        jpmml-converter 1.4.5
        pmml-model 1.5.16

i also checked the code and doubt if the datatype are all parsed to integer and float

![image](https://user-images.githubusercontent.com/776123/147375693-c7c52244-1163-4739-8349-9c8281607e48.png)

**Comment by vruusmann** [comment]
>  i used spark 3.0.1 and these jpmml poms:
> jpmml-sparkml 1.6.6
> jpmml-converter 1.4.5

JPMML-SparkML version 1.6.6 requires JPMML-Converter version 1.4.10:
https://github.com/jpmml/jpmml-sparkml/blob/1.6.6/pom.xml#L65-L75

It won't work with JPMML-Converter version 1.4.5. Where did you get the idea that you should forcibly pair those two?

I'm actually surprised that your application didn't fail sooner with some `ClassNotFoundException` or similar.

You only need to depend on the JPMML-SparkML version 1.6.6 library. It shall pull in the correct versions of all the supporting JPMML libraris as needed.
