### ISSUE TITLE
py4j.protocol.Py4JError: org.jpmml.sparkml.PMMLBuilder does not exist in the JVM

### ISSUE THREAD

**Issue by Tangjiandd** [jpmml/jpmml-sparkml#125]
ERROR:root:Exception while sending command.
Traceback (most recent call last):
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_136476/container_e44_1660093324927_136476_02_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py"", line 1159, in send_command"
"raise Py4JNetworkError(""Answer from Java side is empty"")"
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
""
"During handling of the above exception, another exception occurred:"
""
Traceback (most recent call last):
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_136476/container_e44_1660093324927_136476_02_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py"", line 985, in send_command"
response = connection.send_command(command)
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_136476/container_e44_1660093324927_136476_02_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py"", line 1164, in send_command"
"""Error while receiving"", e, proto.ERROR_ON_RECEIVE)"
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
"File ""gbdt_train.py"", line 185, in <module>"
"g.save_model(""hdfs:///user/tangjian/lightgbm/model/"")"
"File ""gbdt_train.py"", line 99, in save_model"
"pmmlBuilder = PMMLBuilder(sparksession.sparkContext, df_train, self.piplemodel)"
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_136476/container_e44_1660093324927_136476_02_000001/tmp/py37_spark_2.tar.gz/lib/python3.7/site-packages/pyspark2pmml/__init__.py"", line 12, in __init__"
javaPmmlBuilderClass = sc._jvm.org.jpmml.sparkml.PMMLBuilder
"File ""/mnt/disk11/yarn/usercache/flowagent/appcache/application_1660093324927_136476/container_e44_1660093324927_136476_02_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py"", line 1598, in __getattr__"
py4j.protocol.Py4JError: org.jpmml.sparkml.PMMLBuilder does not exist in the JVM

I use the jpmml-sparkml 2.2.0 and get the error above.

**Comment by vruusmann** [comment]
User @Tangjiandd has been blocked for spamming.
