### ISSUE TITLE
2.x jars missing from Maven Central

### ISSUE THREAD

**Issue by jsduncan2** [jpmml/jpmml-sparkml#130]
I'm getting the following error when trying to add jpmml-sparkml to my POM.
```
Could not resolve dependencies for project com.mycompany.app:my-app:jar:1.0-SNAPSHOT: Could not find artifact org.jpmml:jpmml-sparkml:jar:2.2.0 in central (https://repo.maven.apache.org/maven2)
```

I checked Maven Central and I'm seeing poms but no jars.
https://repo1.maven.org/maven2/org/jpmml/jpmml-sparkml/2.2.0/

**Comment by vruusmann** [comment]
The JPMML-SparkML project was modularized during the upgrade from 1.X to 2.X. The coordinates of the main module is `org.jpmml:pmml-sparkml:${version}`.

And all my Maven Central Repository deployments are always complete - the MCR simply doesn't accept incomplete submissions.

Link here:
https://repo1.maven.org/maven2/org/jpmml/pmml-sparkml/2.2.0/

**Comment by vruusmann** [comment]
When in doubt, then my suggestion is to copy&paste dependency declarations from the README file:
https://github.com/jpmml/jpmml-sparkml#library

**Comment by jsduncan2** [comment]
Thank you for the quick response! I'm not sure how I missed that.
