### ISSUE TITLE
Maven Dependency For JPMML Libraries

### ISSUE THREAD

**Issue by SushantVarshney** [jpmml/jpmml-sparkml#24]
I want to use jpmml libraries in my project through maven repositories. Currently,I am using it by installing jpmml jar in my system m2 directory,but want direct links from maven

**Comment by vruusmann** [comment]
RTFM:
https://github.com/jpmml/jpmml-sparkml#library

All JPMML-SparkML release versions are available via Maven Central repository:
http://repo1.maven.org/maven2/org/jpmml/jpmml-sparkml/
