### ISSUE TITLE
Custom Estimator to add to JPMML-SPARKML

### ISSUE THREAD

**Issue by fatihtekin** [jpmml/jpmml-sparkml#28]
Hi

I do have a custom estimator that merges rare categorical values into one value as 'RARE' so that I can group all the rare labels as together. I would like to know if it is possible and how can I add my custom modelconverter as you did for spark standard ml-features.

Ti give an example my custom estimator handles rare columns for categorical columns. So, if there are 1000 categories and only 30 of them are used in most of the time the rest 970 columns will be marked as RARE. So in my model I only save the rare labels. If you need I can paste the code itself as well.

Even if I manage it, I am not sure if jpmml-evaluater will be able to make it run.

**Comment by vruusmann** [comment]
> I do have a custom estimator that merges rare categorical values into one value as 'RARE' so that I can group all the rare labels as together.

Basically, you want to perform mapping between discrete values - map "popular" values back to themselves, and all "unpopular" values to some default value.

The PMML specification provides the [`MapValues` element](http://dmg.org/pmml/v4-3/Transformations.html#xsdElement_MapValues) exactly for this purpose:
```XML
<MapValues name="simplified_color" defaultValue="rare" outputColumn="outputValue">
  <FieldColumnPair field="color" column="inputValue"/>
  <InlineTable>
    <row>
      <inputValue>red</inputValue>
      <outputValue>red</outputValue>
    </row>
    <row>
      <inputValue>yellow</inputValue>
      <outputValue>yellow</outputValue>
    </row>
    <row>
      <inputValue>green</inputValue>
      <outputValue>green</outputValue>
    </row>
  </InlineTable>
</MapValues>
```

The above transformation would keep color values "red", "yellow" and "green" as-is, and change all other color values to "rare" (note the `MapValues@defaultValue` attribute).

> I would like to know if it is possible and how can I add my custom modelconverter as you did for spark standard ml-features.

Here's a code example about generating a `MapValues` element-based transformation:
https://github.com/jpmml/jpmml-sparkml/blob/master/src/main/java/org/jpmml/sparkml/feature/VectorIndexerModelConverter.java

The `org.dmg.pmml.InlineTable` element is rather tricky to generate in Java, because you need to be working with low-level W3C DOM APIs in some point.

> Even if I manage it, I am not sure if jpmml-evaluater will be able to make it run.

JPMML-Evaluator is able to run all PMML documents that conform to PMML 3.X and 4.X specifications.

**Comment by fatihtekin** [comment]
This is a good suggestion, I will try that. I am it is not relevant but is it normal that some of the categorical columns are missing when I generate pmml model?

**Comment by fatihtekin** [comment]
Ok, I got it, sorry. The ones not used for mining got cleaned in DataDictionaryCleaner. 
I will keep this open till I finish my custom converter as I may have more questions.

**Comment by vruusmann** [comment]
Some more code examples - here's the `LabelEncoder` transformer from Scikit-Learn, which maps category values to category indexes:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/preprocessing/LabelEncoder.java

If your data column contains missing values, and you'd like to map them to the default category (or some special category) as well, then don't forget to specify the `MapValues@mapMissingTo` attribute.

Anyway, I would recommend you to take the following steps:

1. Export your Apache Spark ML pipeline into a PMML document.
2. Modify this PMML document manually - define the `MapValues` element, and replace all the `color` field invocations with the `simplified_color` field invocations.
3. Run this modified PMML document using the `org.jpmml.evaluator.EvaluationExample` command-line application from the JPMML-Evaluator project. This is the fastest way to ensure that your PMML changes are structurally valid, and produce desired results.
4. When step 3 is complete, implement the PMML transformation as `org.jpmml.sparkml.FeatureConverter` subclass.

**Comment by fatihtekin** [comment]
Can I assume since I set setHandleInvalid("keep")  in StringIndexer, it will already be handled?

**Comment by vruusmann** [comment]
> I use StringIndexer after my RareMerger

After `RangeMerger`, there will be only "valid and popular" values left - "red", "yellow", "green" and "rare".

There is no need to specify `StringIndexer#handleInvalid` property.

**Comment by fatihtekin** [comment]
I have tried evaulator but i am getting an exception. 

```
Exception in thread "main" java.lang.IllegalArgumentException: Expected 7 features, got 6 features
	at org.jpmml.sparkml.ModelConverter.encodeSchema(ModelConverter.java:147)
	at org.jpmml.sparkml.ModelConverter.registerModel(ModelConverter.java:161)
	at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:76)
	at org.apache.spark.ml.pmml.PmmlTries$.main(PmmlTries.scala:55)
	at org.apache.spark.ml.pmml.PmmlTries.main(PmmlTries.scala)
```

    ```
val conf = new SparkConf().setAppName("OneHotEncoderExample").setMaster("local[*]")
    val sc = new SparkContext(conf)
    val sqlContext = new SQLContext(sc)

    var df = sqlContext.createDataFrame(Seq(
      //(0, 1),
      (1, 3, 1),
      (2, 3, 0),
      (3, 5, 1),
      (4, 5, 1),
      (5, 6, 0),
      (6, 6, 0),
      (7, 6, 0),
      (8, 999999, 1)
      ,(9, 8999, 0)
      ,(10, 89994343, 1)

    )).toDF("id", "category", "label")

    val indexer = new StringIndexer().setInputCol("category").setOutputCol("categoryIndex").setHandleInvalid("keep")
    val encoder = new OneHotEncoder().setInputCol("categoryIndex").setOutputCol("categoryVec").setDropLast(false)
    val assembler = new VectorAssembler().setInputCols(Array("categoryVec")).setOutputCol("features")
    val lr = new LinearRegression()
      .setMaxIter(10)
      .setRegParam(0.3)
      .setElasticNetParam(0.8)

    var pipeline = new Pipeline().setStages(Array(indexer, encoder, assembler, lr))
    var model = pipeline.fit(df)

    model.transform(df).show(10,false)

    var pmml = ConverterUtil.toPMML(df.schema, model)


```

**Comment by fatihtekin** [comment]
sure, spark is 2.2.0 and scala is  2.11

**Comment by vruusmann** [comment]
The culprit is `StringIndexer#setHandleInvalid("keep")`, which causes a special "catch-all-invalids" feature to be appended to the feature list.

The "keep" invalid feature handler seems to be Apache Spark 2.2.X thing. Earlier Apache Spark versions (eg. 2.0.X and 2.1.X) will not let you use it:
```
java.lang.IllegalArgumentException: strIdx_b78325d25068 parameter handleInvalid given invalid value keep.
```

As explained in https://github.com/jpmml/jpmml-sparkml/issues/28#issuecomment-321789670, there is no need to specify invalid value handler after you've explicitly categorized features as "popular" and "rare" using the `RangeMerger` transformer.

Anyway, I intend to make the JPMML-SparkML library smarter about the `StringIndexer#handleInvalid` property. At minimum, there will be a more relevant and informative exception being thrown.

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: 
> org.jpmml.converter.ModelUtil.createMiningSchema(Lorg/jpmml/converter/Schema;)Lorg/dmg/pmml/MiningSchema;

You have a classpath conflict - Apache Spark contains JPMML-Model library version 1.2.15, which is "shadowing" the latest JPMML-Model 1.3.X.

Please configure your application classpath as specified in JPMML-SparkML README file:
https://github.com/jpmml/jpmml-sparkml#library

Personally, I would suggest deleting the offending JPMML-Model library JAR files from the Apache Spark installation (as detailed in section "Modifying Apache Spark installation").

**Comment by fatihtekin** [comment]
I have checked the dependencies after excluding pmml-model as below and still got the same error
  "org.apache.spark" %% "spark-mllib" % "2.2.0" exclude("org.jpmml", "pmml-model"),

<img width="430" alt="screen shot 2017-08-12 at 15 14 16" src="https://user-images.githubusercontent.com/3455853/29241000-1e52ad08-7f71-11e7-9b45-00c2df17d6bc.png">

<img width="433" alt="screen shot 2017-08-12 at 15 16 43" src="https://user-images.githubusercontent.com/3455853/29241011-55365040-7f71-11e7-88fa-a108dc5c016e.png">

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: Expected 7 features, got 6 features

The name of the "catch-all-invalids" pseudo-category is `__unknown`. The fix is available in JPMML-SparkML version 1.3.2 (and newer).

In PMML, the corresponding transformation looks like this:
```XML
<DerivedField name="handleInvalid(category)" optype="categorical" dataType="string">
	<Apply function="if">
		<Apply function="isIn">
			<FieldRef field="category"/>
			<Constant>6</Constant>
			<Constant>5</Constant>
			<Constant>3</Constant>
			<Constant>8999</Constant>
			<Constant>89994343</Constant>
			<Constant>999999</Constant>
		</Apply>
		<FieldRef field="category"/>
		<Constant>__unknown</Constant>
	</Apply>
</DerivedField>
```

You could use exactly the same pattern for the `RangeMerger` - simply replace `__unknown` with `rare`.

**Comment by fatihtekin** [comment]
I have added my RareMerger as I have realized that I have missed explaining the null value handling as well. Perhaps code speaks better than words. Please let me know if I need to explain more. 
I think I will need to transform  all rare labels to 'RARE', popular labels stays as they are, if training have seen null values then they get translated into category level 'NULL' if not they go to __unknown. 

Implementation
[RareMerger.txt](https://github.com/jpmml/jpmml-sparkml/files/1221623/RareMerger.txt)

Test Cases (Standard as Spark Test its ML features)
[RareMergerSuite.txt](https://github.com/jpmml/jpmml-sparkml/files/1221625/RareMergerSuite.txt)

**Comment by vruusmann** [comment]
> I assume your implementation for StringIndexerModelCOnvertor might throw IllegalArgumentException in case setHandleInvalid("skip") is set.

PMML does not have "skip" functionality. If the PMML engine is asked to score a data record, then the scoring either 1) succeeds or 2) fails with some sort of exception. The "skip" option would mean that the PMML engine doesn't succeed or fail - just consumes a data record.

> Unfortunately, I am getting below exception.
> Exception in thread "main" java.lang.NumberFormatException: For input string: "__unknown"

The constant `__unknown` is a string value. If you're going to do `StringIndexer#setHandleInvalid("keep")`, then you should make sure that your column is of string data type.

It's a Apache Spark design decision (see the source code of the `StringIndexer` transformer). A possible workaround would be that `__unknown` should be replaced with some sort other constant for numeric values (perhaps `-999`).

> I will need to transform all rare labels to 'RARE', popular labels stay as they are, if training has seen null values then they get translated into category level 'NULL' if not they go to __unknown.

In the above `DerivedField` element, simply specify the `mapMissingTo` attribute:
```XML
<DerivedField name="handleInvalid(category)" mapMissingTo="NULL" optype="categorical" dataType="string">
</DerivedField>
```

**Comment by fatihtekin** [comment]
I do have another issue which is jpmml-evaluator is using com.google.guava:guava:20.0 and spark is using 11.0.2. If I use either of them I am either having 
`Exception in thread "main" java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat
`
or
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilderSpec
	at org.jpmml.evaluator.CacheUtil.<clinit>(CacheUtil.java:112)
	at org.jpmml.evaluator.ModelEvaluator.<clinit>(ModelEvaluator.java:671)
	at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:103)
	at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:66)
	at org.apache.spark.ml.pmml.PmmlTries$.main(PmmlTries.scala:60)
	at org.apache.spark.ml.pmml.PmmlTries.main(PmmlTries.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheBuilderSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

**Comment by fatihtekin** [comment]
I got it sorted as using below in case someone else also needs below is the added to the build.sbt plugin

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.guava**" -> "shadeio.@1").inAll
)

**Comment by fatihtekin** [comment]
When I use below RareMergerModelConverter, I am getting exception at StringIndexerModelConverter. Could you tell me what I am doing wrong?


```
Exception in thread "main" java.lang.IllegalArgumentException: categoryMerge
	at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:145)
	at org.jpmml.sparkml.feature.StringIndexerModelConverter.encodeFeatures(StringIndexerModelConverter.java:54)
	at org.jpmml.sparkml.FeatureConverter.registerFeatures(FeatureConverter.java:47)
	at org.jpmml.sparkml.ConverterUtil.toPMML(ConverterUtil.java:75)

```

Code

```
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.dmg.pmml.*;
import org.jpmml.converter.ContinuousFeature;
import org.jpmml.converter.DOMUtil;
import org.jpmml.converter.Feature;
import org.jpmml.sparkml.FeatureConverter;
import org.jpmml.sparkml.SparkMLEncoder;
import org.apache.spark.ml.pmml.RareMergerModel;
import javax.xml.parsers.DocumentBuilder;

public class RareMergerModelConverter extends FeatureConverter<RareMergerModel> {

	public RareMergerModelConverter(RareMergerModel transformer){
		super(transformer);
	}

	@Override
	public List<Feature> encodeFeatures(SparkMLEncoder encoder){
		RareMergerModel transformer = getTransformer();
		Feature feature = encoder.getOnlyFeature(transformer.getInputCol());
		List<String> columns = Arrays.asList("inputValue", "outputValue");
		InlineTable inlineTable = new InlineTable();
        DocumentBuilder documentBuilder = DOMUtil.createDocumentBuilder();

		for(String popularLabel : transformer.popularLabels()){
            Row row = DOMUtil.createRow(documentBuilder, columns, Arrays.asList(popularLabel, popularLabel));
            inlineTable.addRows(row);
        }

        for(String rareLabel : transformer.rareLabels()){
            Row row = DOMUtil.createRow(documentBuilder, columns, Arrays.asList(rareLabel, transformer.rareLabel()));
            inlineTable.addRows(row);
        }

        MapValues mapValues = new MapValues()
				.addFieldColumnPairs(new FieldColumnPair(feature.getName(), columns.get(0)))
				.setOutputColumn(columns.get(1))
				.setInlineTable(inlineTable)
                .setDefaultValue("__unknown");

        mapValues.setMapMissingTo("__unknown");
        if(transformer.isNullLabelAdded()){
            mapValues.setMapMissingTo("NULL");
        }

        DerivedField derivedField = encoder.createDerivedField(formatName(transformer), OpType.CONTINUOUS, DataType.STRING, mapValues);
        return Collections.<Feature>singletonList(new ContinuousFeature(encoder, derivedField));
	}
}
```

**Comment by vruusmann** [comment]
> When I use below RareMergerModelConverter, ...

Your `RareMergerModelConverter` class is close to perfect. Looks like you've successfully managed to figure out a great deal of JPMML-SparkML API design and architecture principles on your own.

One issue that I'm seeing with your code is that the operational type of the derived field should probably be `OpType.CATEGORICAL` (not `OpType.CONTINUOUS`), because string values do not have comparison operations (eg. "<", "<=", ">=", ">") defined for them. Following this thought, the generated feature should be an instance of `CategoricalFeature` (not `ContinuousFeature`).

> ... I am getting exception at StringIndexerModelConverter.

The trouble is that JPMML-SparkML assumes that `StringIndexerModel` will always be the first transformer in the pipeline (for a particular column). This assumption is hard-coded in the form, that the corresponding column name must resolve to a `DataField` element. In your case, `StringIndexerModel` is the second transformer in the pipeline (following the `RareMergerModel` transformer), and the corresponding column name resolves to a `DerivedField` element.

Class `StringIndexerModelConverter` should contain a special `instanceof` check to handle this situation. Essentially, if `feature instanceof CategoricalFeature` evaluates to true, then there is no need to invoke the `#toCategorical(...)` logic anymore.

**Comment by vruusmann** [comment]
So, what's the solution now?

Your `RareMerger` use case is almost completely handled by the `StringIndexer#setHandleInvalid("keep")`; the only addition is that you want to be replacing missing values with the `__unknown` constant.

I would still advise you to stop pursuing this `RareMerger` path, because it adds unnecessary complexity to your project/application. In PMML, you're supposed to use the `MiningField@missingValueReplacement` attribute for missing value replacement functionality:

```XML
<RegressionModel>
	<MiningSchema>
		<MiningField name="category" missingValueReplacement="__unknown"/>
	</MiningSchema>
</RegressionModel>
```

You can add/modify/remove PMML elements and attributes using JPMML-Model library (eg. using the very functional and powerful Visitors API). There is no need to change anything in the Apache Spark ML side.

Here's the pattern:
```Java
PipelineModel pipelineModel = pipeline.fit(df);

org.dmg.pmml.PMML pmml = ConverterUtil.toPMML(df.schema, pipelineModel);
pmml = performApplicationSpecificCustomizations(pmml); // THIS!
JAXBUtil.marshalPMML(pmml, System.out);
```

In this fictional `performApplicationSpecificCustomizations` utility method you can modify the live `org.dmg.pmml.PMML` class model object in any way you want.

**Comment by fatihtekin** [comment]
Unfortunately, I have to group the rare ones and unknown ones separately so just using stringindexer with the limited group as you suggested won't be enough. Another thing is that I will have to write another transformer again so I prefer to write another converter for now.

**Comment by fatihtekin** [comment]
Is it possible for you to support StringIndexerModelConverter, in case there is another transformer/estimator before? So that I don't need to maintain StringIndexerModelConverter. Maybe also good for future when needed

**Comment by fatihtekin** [comment]
Currently, I am doing reflection but I believe you have a better solution :) 

       ```
 DataField dataField;
		if(feature instanceof CategoricalFeature){
            try {
                java.lang.reflect.Field field = getField(encoder.getClass(), "dataFields");
                Map<FieldName, DataField> dataFields = (Map<FieldName, DataField>)(field.get(encoder));
                dataField = dataFields.entrySet().iterator().next().getValue();
            } catch (IllegalAccessException e) {
                throw new IllegalStateException(e);
            }
		}else{
            dataField = encoder.toCategorical(feature.getName(), labels);
        }
```
