### ISSUE TITLE
Need to Export Pipeline Without Specifying Model

### ISSUE THREAD

**Issue by sfahad1414** [jpmml/jpmml-sparkml#61]
We had done modeling in tensorflow using keras and export the model and hosting it using DL4J. but before the model gets hits we need to do some preprocessing so we had made a pipeline using spark for which contains string indexer, standard scaler and vectorizer but does not contain any modeling like regression or classification. when we try to export Pipeline got Error Message Expected a pipeline with one or more models, got a pipeline with zero models, maybe it should allow exporting pipeline with transformation steps.

**Comment by vruusmann** [comment]
See https://github.com/jpmml/jpmml-sklearn/issues/86
