### ISSUE TITLE
PMML for custom transformers

### ISSUE THREAD

**Issue by avisheknag17** [jpmml/jpmml-sparkml#72]
Is it possible to add custom transformer in pipeline ?
For example, in a NLP problem, if I want to clean text before classification, Can I add a seperate a transformer and put it in my pipeline and then export to PMML by this API ?

**Comment by vruusmann** [comment]
> Is it possible to add custom transformer in pipeline ?

Yes you can:

1. Write the transformer class in Scala.
2. Write the corresponding transformer-to-pmml-converter class in Java/Scala. In most cases, subclassing `org.jpmml.sparkml.FeatureConverter` is the way to go.
3. Add the above class to your application classpath, and register it with the JPMML-SparkML runtime by  mentioning it in some `META-INF/sparkml2pmml.properties` file: https://github.com/jpmml/jpmml-sparkml/blob/master/src/main/resources/META-INF/sparkml2pmml.properties#L1-L28

**Comment by avisheknag17** [comment]
For example, if the text cleaning library is written in Python (Gensim). Can I directly add that in this API ? Or there also I have to first replicate the logic into Java/Scala for writing the custom transformer ?

**Comment by vruusmann** [comment]
> The text cleaning library is written in Python (Gensim). Can I directly add that in this API?

You can call Gensim API directly in your Scala transformer class.

PMML does not have the concept of "including a library". Therefore, you cannot reference/call external Gensim API functions from within a PMML document; you'd need to translate the relevant Gensim method bodies into PMML markup.

Of course, even though the PMML specification itself does not have the concept of "including a library", then individual PMML scoring engines may offer this functionality. For example, the JPMML-Evaluator library allows you to call arbitrary 3rd party Java/JVM libraries. Something like this:
```xml
<Apply function="my.company.MyGensimFunction">
  <FieldRef field="text_feature_id"/>
</Apply>
```

In the above case, you could have 95% of your prediction logic expressed as pure PMML, and only import this missing 5%.
