### ISSUE TITLE
Support for map function within SQLTransformer

### ISSUE THREAD

**Issue by tyers** [jpmml/jpmml-sparkml#82]
Provide the ability to lookup keys to values within SQLTransformer by potentially providing support for the [map function](https://spark.apache.org/docs/2.3.0/api/sql/index.html#map) provided by SparkSQL.

**Comment by vruusmann** [comment]
Example SQL expression that would demonstrate a map-based lookup?

The catalog of [Apache Spark SQL functions](https://spark.apache.org/docs/2.4.0/api/sql/index.html) doesn't seem to provide any functions that take a `map` as an argument.

**Comment by tyers** [comment]
> The catalog of [Apache Spark SQL functions](https://spark.apache.org/docs/2.4.0/api/sql/index.html) doesn't seem to provide any functions that take a `map` as an argument.
Seems i have misinterpreted the docs on this one and the only way to achieve this would be via a UDF of some kind.

**Comment by vruusmann** [comment]
> the only way to achieve this would be via a UDF of some kind

Got the same impression. Right now, you can perform category re-mapping using the `CASE-WHEN` statement.

The JPMML-SparkML does not provide any custom transformer classes. Once there's a precedent, it would be possible to expand the framework into other areas as well, such as providing custom UDFs for `map`-based functionality.
