### ISSUE TITLE
How to get features in encodeFeatures method of VectorIndexerModelConverter?

### ISSUE THREAD

**Issue by hibayesian** [jpmml/jpmml-sparkml#9]
Suppose we obtained a VectorIndexerModel with a param inputCol = "features" which specifies the name of input column(its type is Vector). Now how to get features in encodeFeatures method of VectorIndexerModelConverter?

It seems that this project doesn't support Vector type. 

Looking forward to your reply. Thanks!

**Comment by vruusmann** [comment]
> Suppose we obtained a VectorIndexerModel with a param inputCol = "features" which specifies the name of input column(its type is Vector). Now how to get features in encodeFeatures method of VectorIndexerModelConverter?

```
SparkMLEncoder encoder = ...;
VectorIndexerModel vectorIndexerModel = ...;
VectorIndexerModelConverter vectorIndexerModelConverter = new VectorIndexerModelConverter(vectorIndexerModel);
List<Feature> features = vectorIndexerModelConverter.encodeFeatures(encoder); // THIS
```

Here's the business logic:
https://github.com/jpmml/jpmml-sparkml/blob/master/src/main/java/org/jpmml/sparkml/feature/VectorIndexerModelConverter.java#L53

This converter class, like all JPMML-SparkML converter classes, has full test coverage. If you build the project locally, then you can find the JaCoCo report in the `target/site/jacoco` directory.

> It seems that this project doesn't support Vector type.

Apache Spark ML uses the Vector data type to represent "a group of columns/features". PMML deals with columns/features directly, and does not need any helper layers.

So, the JPMML-SparkML library represents the Vector type internally as `List<Feature>`. For example, the method `SparkMLEncoder#getFeatures(columnName)` returns a singleton list for scalar-type columns/features, and a multi-element list for vector-type columns/features.
